# Generated by Django 4.0.1 on 2022-03-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('logo', models.ImageField(upload_to='', verbose_name='logo')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='title')),
                ('details', models.TextField(verbose_name='details')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='base.tag')),
            ],
        ),
    ]
